apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45
  selector:
    matchLabels:
      app: hello-world
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: bittedocker/spring-boot-cicd
        imagePullPolicy: IfNotPresent
        ports:
        - name: liveness-port
          containerPort: 8080
        resources: #CHANGE
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 1024Mi #256Mi 
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 5
          periodSeconds: 10
          initialDelaySeconds: 60
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels: #PODS
    app: hello-world
  name: hello-world
  namespace: default
spec:
  ports:
  - # nodePort: 30702 #CHANGE
    port: 8080 #CHANGE
    protocol: TCP
    targetPort: 8080 #CHANGE
  selector:
    app: hello-world
  sessionAffinity: None #CHANGE
  type: LoadBalancer
